name: Publish to PyPI
on: [release]

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - name: Setup python for test ${{ matrix.py }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ 3.11 }}
    - uses: actions/checkout@v3
    - name: Upgrade pip
      run: python -m pip install -U pip
    - name: Install hatch via package
      run: python -m pip install -e '.[dev]'
    - name: Build via hatch
      run: hatch build
    - name: Run via hatch
      run : hatch publish -u ${{ secrets.PYPI_USER }} -a ${{ secrets.PYPI_SECRET_KEY }} --no-prompt
